name: Deploy My Website
on: push

# Permissions (GitHub ko batana padta hai ki hum site upload kar rahe hain)
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Code Lao (Checkout)
        uses: actions/checkout@v3
        
      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Website File Upload karo
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'
          
      - name: Live Server par Deploy karo ðŸš€
        id: deployment
        uses: actions/deploy-pages@v2
